[package]
name = "pongers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
winit = "0.28.3"
wgpu = "0.15.1"
bytemuck = { version = "1.13.1", features = [ "derive" ] }
glam = { version = "0.23.0", features= [ "bytemuck" ]}
tobj = { version = "3.2.4", features = [ "async" ] }

tokio = { version = "1.26.0", features = [ "full" ] }
anyhow = "1.0.70"

[dependencies.image]
version = "0.24.5"
default-features = false
features = ["png", "jpeg"]

[build-dependencies]
anyhow = "1.0.70"
fs_extra = "1.3.0"
glob = "0.3.1"