[package]
name = "pongers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
winit = "0.28.3"
wgpu = "0.15.1"
bytemuck = { version = "1.13.1", features = [ "derive" ] }
glam = { version = "0.23.0", features= [ "bytemuck" ]}

tokio = { version = "1.27.0", features = [ "full" ] }